version: '3.9'

services:
  web:
    container_name: pnews-web
    build:
      context: src/server
      dockerfile: Dockerfile
    ports:
      - "80:80"
    image: purplelemons/pnews-web:latest
    restart: unless-stopped
    volumes:
      - images:/app/images
    tty: true
    depends_on:
      - pnews

  pnews:
    container_name: pnews
    build:
      context: src/new_pnews
      dockerfile: Dockerfile
    image: purplelemons/pnews:latest
    restart: unless-stopped
    volumes:
      - images:/app/images
    shm_size: 2gb
    tty: true


volumes:
  images: {}
